2023-12-31 14:12:55,980 INFO    StreamThr :21192 [internal.py:wandb_internal():86] W&B internal server running at pid: 21192, started at: 2023-12-31 14:12:55.979970
2023-12-31 14:12:55,980 DEBUG   HandlerThread:21192 [handler.py:handle_request():146] handle_request: status
2023-12-31 14:12:55,982 INFO    WriterThread:21192 [datastore.py:open_for_write():85] open: F:\Everything\New_drone\wandb\run-20231231_141255-0ihrguj7\run-0ihrguj7.wandb
2023-12-31 14:12:55,983 DEBUG   SenderThread:21192 [sender.py:send():382] send: header
2023-12-31 14:12:56,009 DEBUG   SenderThread:21192 [sender.py:send():382] send: run
2023-12-31 14:12:56,254 INFO    SenderThread:21192 [dir_watcher.py:__init__():211] watching files in: F:\Everything\New_drone\wandb\run-20231231_141255-0ihrguj7\files
2023-12-31 14:12:56,255 INFO    SenderThread:21192 [sender.py:_start_run_threads():1136] run started: 0ihrguj7 with start time 1704053575.98097
2023-12-31 14:12:56,259 DEBUG   HandlerThread:21192 [handler.py:handle_request():146] handle_request: check_version
2023-12-31 14:12:56,259 DEBUG   SenderThread:21192 [sender.py:send_request():409] send_request: check_version
2023-12-31 14:12:56,479 DEBUG   HandlerThread:21192 [handler.py:handle_request():146] handle_request: run_start
2023-12-31 14:12:56,500 DEBUG   HandlerThread:21192 [system_info.py:__init__():32] System info init
2023-12-31 14:12:56,500 DEBUG   HandlerThread:21192 [system_info.py:__init__():47] System info init done
2023-12-31 14:12:56,500 INFO    HandlerThread:21192 [system_monitor.py:start():194] Starting system monitor
2023-12-31 14:12:56,501 INFO    SystemMonitor:21192 [system_monitor.py:_start():158] Starting system asset monitoring threads
2023-12-31 14:12:56,501 INFO    HandlerThread:21192 [system_monitor.py:probe():214] Collecting system info
2023-12-31 14:12:56,503 INFO    SystemMonitor:21192 [interfaces.py:start():190] Started cpu monitoring
2023-12-31 14:12:56,504 INFO    SystemMonitor:21192 [interfaces.py:start():190] Started disk monitoring
2023-12-31 14:12:56,504 INFO    SystemMonitor:21192 [interfaces.py:start():190] Started gpu monitoring
2023-12-31 14:12:56,510 INFO    SystemMonitor:21192 [interfaces.py:start():190] Started memory monitoring
2023-12-31 14:12:56,515 INFO    SystemMonitor:21192 [interfaces.py:start():190] Started network monitoring
2023-12-31 14:12:56,541 DEBUG   HandlerThread:21192 [system_info.py:probe():196] Probing system
2023-12-31 14:12:56,542 DEBUG   HandlerThread:21192 [system_info.py:_probe_git():181] Probing git
2023-12-31 14:12:56,585 ERROR   HandlerThread:21192 [gitlib.py:root():92] git root error: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: detected dubious ownership in repository at 'F:/Everything/New_drone'
'F:/Everything/New_drone' is on a file system that does not record ownership
To add an exception for this directory, call:

	git config --global --add safe.directory F:/Everything/New_drone'
2023-12-31 14:12:56,585 DEBUG   HandlerThread:21192 [system_info.py:_probe_git():189] Probing git done
2023-12-31 14:12:56,585 DEBUG   HandlerThread:21192 [system_info.py:probe():244] Probing system done
2023-12-31 14:12:56,585 DEBUG   HandlerThread:21192 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22000-SP0', 'python': '3.9.2', 'heartbeatAt': '2023-12-31T20:12:56.541981', 'startedAt': '2023-12-31T20:12:55.809967', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': 'F:\\Everything\\New_drone\\loading_main.py', 'codePathLocal': 'loading_main.py', 'codePath': 'loading_main.py', 'git': {'remote': 'https://github.com/Samuel-Fipps/airSim_Drone.git', 'commit': None}, 'email': 'samuelfipps@gmail.com', 'root': 'F:\\Everything\\New_drone', 'host': 'DESKTOP-VP5KEII', 'username': '14055', 'executable': 'C:\\Users\\14055\\AppData\\Local\\Programs\\Python\\Python39\\python.exe', 'cpu_count': 16, 'cpu_count_logical': 24, 'cpu_freq': {'current': 3418.0, 'min': 0.0, 'max': 3418.0}, 'cpu_freq_per_core': [{'current': 3418.0, 'min': 0.0, 'max': 3418.0}], 'disk': {'/': {'total': 953.8515625, 'used': 147.343505859375}}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 2, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 127.79042434692383}}
2023-12-31 14:12:56,585 INFO    HandlerThread:21192 [system_monitor.py:probe():224] Finished collecting system info
2023-12-31 14:12:56,585 INFO    HandlerThread:21192 [system_monitor.py:probe():227] Publishing system info
2023-12-31 14:12:56,585 DEBUG   HandlerThread:21192 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-12-31 14:12:56,587 DEBUG   HandlerThread:21192 [system_info.py:_save_pip():68] Saving pip packages done
2023-12-31 14:12:56,587 DEBUG   HandlerThread:21192 [system_info.py:_save_code():90] Saving code
2023-12-31 14:12:56,606 ERROR   HandlerThread:21192 [gitlib.py:root():92] git root error: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: detected dubious ownership in repository at 'F:/Everything/New_drone'
'F:/Everything/New_drone' is on a file system that does not record ownership
To add an exception for this directory, call:

	git config --global --add safe.directory F:/Everything/New_drone'
2023-12-31 14:12:56,636 DEBUG   HandlerThread:21192 [system_info.py:_save_code():111] Saving code done
2023-12-31 14:12:56,637 DEBUG   HandlerThread:21192 [system_info.py:_save_patches():128] Saving git patches
2023-12-31 14:12:56,655 ERROR   HandlerThread:21192 [gitlib.py:root():92] git root error: Cmd('git') failed due to: exit code(128)
  cmdline: git rev-parse --show-toplevel
  stderr: 'fatal: detected dubious ownership in repository at 'F:/Everything/New_drone'
'F:/Everything/New_drone' is on a file system that does not record ownership
To add an exception for this directory, call:

	git config --global --add safe.directory F:/Everything/New_drone'
2023-12-31 14:12:57,259 INFO    Thread-16 :21192 [dir_watcher.py:_on_file_created():271] file/dir created: F:\Everything\New_drone\wandb\run-20231231_141255-0ihrguj7\files\code\loading_main.py
2023-12-31 14:12:57,259 INFO    Thread-16 :21192 [dir_watcher.py:_on_file_created():271] file/dir created: F:\Everything\New_drone\wandb\run-20231231_141255-0ihrguj7\files\requirements.txt
2023-12-31 14:12:57,259 INFO    Thread-16 :21192 [dir_watcher.py:_on_file_created():271] file/dir created: F:\Everything\New_drone\wandb\run-20231231_141255-0ihrguj7\files\code
2023-12-31 14:12:57,273 INFO    WriterThread:21192 [datastore.py:close():294] close: F:\Everything\New_drone\wandb\run-20231231_141255-0ihrguj7\run-0ihrguj7.wandb
2023-12-31 14:12:57,480 INFO    SenderThread:21192 [sender.py:finish():1548] shutting down sender
2023-12-31 14:12:57,480 INFO    SenderThread:21192 [dir_watcher.py:finish():358] shutting down directory watcher
2023-12-31 14:12:58,274 INFO    SenderThread:21192 [dir_watcher.py:finish():388] scan: F:\Everything\New_drone\wandb\run-20231231_141255-0ihrguj7\files
2023-12-31 14:12:58,274 INFO    SenderThread:21192 [dir_watcher.py:finish():402] scan save: F:\Everything\New_drone\wandb\run-20231231_141255-0ihrguj7\files\config.yaml config.yaml
2023-12-31 14:12:58,275 INFO    SenderThread:21192 [dir_watcher.py:finish():402] scan save: F:\Everything\New_drone\wandb\run-20231231_141255-0ihrguj7\files\requirements.txt requirements.txt
2023-12-31 14:12:58,277 INFO    SenderThread:21192 [dir_watcher.py:finish():402] scan save: F:\Everything\New_drone\wandb\run-20231231_141255-0ihrguj7\files\code\loading_main.py code/loading_main.py
2023-12-31 14:12:58,277 INFO    SenderThread:21192 [file_pusher.py:finish():175] shutting down file pusher
2023-12-31 14:12:58,277 INFO    SenderThread:21192 [file_pusher.py:join():181] waiting for file pusher
2023-12-31 14:12:58,664 INFO    wandb-upload_0:21192 [upload_job.py:push():131] Uploaded file F:\Everything\New_drone\wandb\run-20231231_141255-0ihrguj7\files\config.yaml
2023-12-31 14:12:58,667 INFO    wandb-upload_1:21192 [upload_job.py:push():131] Uploaded file F:\Everything\New_drone\wandb\run-20231231_141255-0ihrguj7\files\requirements.txt
2023-12-31 14:12:58,733 INFO    wandb-upload_2:21192 [upload_job.py:push():131] Uploaded file F:\Everything\New_drone\wandb\run-20231231_141255-0ihrguj7\files\code\loading_main.py
2023-12-31 14:12:59,289 INFO    SenderThread:21192 [file_stream.py:finish():595] file stream finish called
2023-12-31 14:12:59,414 INFO    SenderThread:21192 [file_stream.py:finish():599] file stream finish is done
2023-12-31 14:12:59,571 ERROR   StreamThr :21192 [internal.py:wandb_internal():174] Thread HandlerThread:
Traceback (most recent call last):
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\internal_util.py", line 49, in run
    self._run()
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\internal_util.py", line 100, in _run
    self._process(record)
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\internal.py", line 279, in _process
    self._hm.handle(record)
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\handler.py", line 138, in handle
    handler(record)
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\handler.py", line 148, in handle_request
    handler(record)
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\handler.py", line 683, in handle_request_run_start
    self._system_monitor.probe(publish=True)
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\system\system_monitor.py", line 228, in probe
    self.system_info.publish(system_info)
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 255, in publish
    self._save_patches()
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\internal\system\system_info.py", line 146, in _save_patches
    upstream_commit = self.git.get_upstream_fork_point()
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\wandb\sdk\lib\gitlib.py", line 200, in get_upstream_fork_point
    possible_relatives.append(tracking_branch.commit)
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\git\refs\symbolic.py", line 226, in _get_commit
    obj = self._get_object()
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\git\refs\symbolic.py", line 219, in _get_object
    return Object.new_from_sha(self.repo, hex_to_bin(self.dereference_recursive(self.repo, self.path)))
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\git\objects\base.py", line 94, in new_from_sha
    oinfo = repo.odb.info(sha1)
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\git\db.py", line 40, in info
    hexsha, typename, size = self._git.get_object_header(bin_to_hex(binsha))
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\git\cmd.py", line 1383, in get_object_header
    return self.__get_object_header(cmd, ref)
  File "C:\Users\14055\AppData\Local\Programs\Python\Python39\lib\site-packages\git\cmd.py", line 1369, in __get_object_header
    cmd.stdin.flush()
OSError: [Errno 22] Invalid argument
